#!/bin/sh
# The TCP Scanner (tcp-scan) is Copyright (C) 2003-2008 Roy Hills,
# NTA Monitor Ltd.
#
# This file is part of tcp-scan.
#
# tcp-scan is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# tcp-scan is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with tcp-scan.  If not, see <http://www.gnu.org/licenses/>.
#
# check-tcp-scan-run1 -- Shell script to test tcp-scan basic functionality
#
# Author: Roy Hills
# Date: 9 March 2006
#
# This shell script checks that "tcp-scan --help" and "tcp-scan --version"
# work.  These options don't use much of the tcp-scan functionallity, so if
# they fail, then there is a fundimental problem with the program.
#
TMPFILE=/tmp/tcp-scan-test.$$.tmp
#
echo "Checking tcp-scan --help ..."
./tcp-scan --help 2> $TMPFILE
if test $? -ne 0; then
   rm -f $TMPFILE
   echo "FAILED"
   exit 1
fi
grep '^Report bugs or send suggestions at ' $TMPFILE >/dev/null
if test $? -ne 0; then
   rm -f $TMPFILE
   echo "FAILED"
   exit 1
fi
echo "ok"
#
echo "Checking tcp-scan --version ..."
./tcp-scan --version 2> $TMPFILE
if test $? -ne 0; then
   rm -f $TMPFILE
   echo "FAILED"
   exit 1
fi
grep '^Copyright (C) ' $TMPFILE >/dev/null
if test $? -ne 0; then
   rm -f $TMPFILE
   echo "FAILED"
   exit 1
fi
echo "ok"
#
rm -f $TMPFILE
