name: coverage
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: install libpcap
        run: |
          sudo apt-get update -qq
          sudo apt-get install -qq libpcap0.8-dev 
      - name: install cpp-coveralls
        run: sudo pip install cpp-coveralls
      - name: autoreconf
        run: autoreconf --install
      - name: configure with gcov
        run: ./configure --enable-gcov
      - name: make
        run: make
      - name: make check
        run: make check
      - name: run coveralls
        run: coveralls
      
